---
- hosts: all
  #gather_facts: false
  roles:
    - common

  tasks:
    - name: Delete all .tgz.gpg files in module cache
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/var/www/html/admin/modules/_cache/*.tgz.gpg"