---
- hosts: "{{ target_hosts | default('all') }}"
  remote_user: root
  gather_facts: no
  tasks:
    - shell: yum check-update | wc -l
      register: count
    - name: Update all packages
      yum: 
        name: "*"
        state: latest
    

    - debug: var=count.stdout_lines
