---
- hosts: all
  gather_facts: yes
  become: false
  tasks:
    - name: System details
      debug:
        msg: "{{ item }}"
      loop:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"
