---
- hosts: all
  gather_facts: yes
  become: false
  tasks:
    - name: Get OS Distribution
      debug:
        msg: "{{ ansible_distribution }}"
    - name: Get OS Distribution Version
      debug:
        msg: "{{ ansible_distribution_version }}"
    - name: Get OS Distribution Major Version
      debug:
        msg: "{{ ansible_distribution_major_version }}"
