---
- name: Install Asternic Devel
  hosts: all
  gather_facts: no
  tasks:
    - name: Clean
      shell: cd /usr/src && rm -rf asternic-stats-*
    - name: Download
      get_url:
        url: "{{ ASTERNIC_DEV_URL }}"
        dest: /usr/src
    - name: Change directory, extract files, and list contents
      shell: cd /usr/src && tar zxvf asternic-stats-*
    - name: Run sudo make install
      expect:
        echo: true
        chdir: /usr/src/asternic-stats-devel-2.3.9
        command: sudo make install
        responses:
          (?i)MySQL root password: ""
          (?i)user: "admin"
        timeout: 60  # Adjust the timeout value as needed (in seconds)
    