---
- name: Install Asternic Devel
  hosts: all
  gather_facts: no
  tasks:
    - name: Clean
      shell: cd /usr/src && rm -rf asternic-stats-*
    - name: Download
      get_url:
        url: "{{ ASTERNIC_DEV_URL }}"
        dest: /usr/src
    - name: Change directory, extract files, and list contents
      shell: cd /usr/src && tar zxvf asternic-stats-*
    - name: Run sudo make install
      expect:
        command: cd /usr/src/asternic-stats-devel-2.3.9 && sudo make install
        responses:
          (?i)password: ''
          (?i)user: 'admin'
      register: expect_output    

    - name: Debug output of expect module
      debug:
        var: expect_output  # Print the output of the expect task