---
- name: Install Asternic Devel
  hosts: all
  gather_facts: no
  tasks:
    # - name: Clean
    #   shell: cd /usr/src && rm -rf asternic-stats-*
    # - name: Download
    #   get_url:
    #     url: "{{ ASTERNIC_DEV_URL }}"
    #     dest: /usr/src
    # - name: Change directory, extract files, and list contents
    #   shell: cd /usr/src && tar zxvf asternic-stats-*
    - name: Run sudo make install
      expect:
        echo: yes
        chdir: /usr/src/asternic-stats-devel-2.3.9
        command: sudo make install
        responses:
          "Please enter the MySQL root password:": ''
          "(?i)Select a password for the 'admin' user:": "admin_password\n"
          "(?i)Confirm the password for the 'admin' user:": "admin_password\n"
        timeout: 120  # Adjust the timeout value as needed (in seconds)
      no_log: false  
      register: __expect_example_result
      ignore_errors: true
    #  failed_when: "expect_example_result.rc != 0 and 'Done' not in expect_example_result.stdout"
    - name: Debug
      debug:
        var: __expect_example_result  # Print the output of the expect task
 