---
- name: Install Asternic Devel
  hosts: all
  gather_facts: no
  tasks:
    - name: Download
      get_url:
        url: "{{ ASTERNIC_DEV_URL }}"
        dest: /usr/src
    - name: Change directory, extract files, and list contents
      command: cd /usr/src && tar zxvf asternic-stats-* && cd asternic-stats-* && ls
      register: ls_output
      ignore_errors: true

    - name: Display ls output and errors
      debug:
        msg: |
          Output:
          {{ ls_output.stdout_lines | default('No output') }}
          Error:
          {{ ls_output.stderr | default('No error') }}  

 