---
- name: Install Asternic Devel
  hosts: "{{ server_name }}"
  gather_facts: no
  tasks:
    - name: Download
      get_url:
        url: "{{ ASTERNIC_DEV_URL }}"
        dest: /usr/src
    - name: cd and execute
      command: cd /usr/src && tar zxvf asternic-stats-* && cd asternic-stats-*
 