---
- name: Install Asternic Devel
  hosts: all
  gather_facts: no
  tasks:
    - name: Download
      get_url:
        url: "{{ ASTERNIC_DEV_URL }}"
        dest: /usr/src
    - name: Change directory, extract files, and list contents
      command: cd /usr/src && tar zxvf asternic-stats-* && cd asternic-stats-*
    - name: Run sudo make install
      expect:
        command: sudo make install
        responses:
          'Please enter the MySQL root password:': "\n"
          'Select a password for the \'admin\' user:': 'your_admin_password\n'
          'Confirm the password for the \'admin\' user:': 'your_admin_password\n'