---
- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Install package foo from repo
    community.general.pacman:
      name: 
      - mc
      - nano
      - wget
      state: present