---
- hosts: localhost
  remote_user: root
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Install package foo from repo
    community.general.pacman:
      name: nano
      state: present
  - name: Shut down Debian flavored systems
    ansible.builtin.command: ls
    when: ansible_facts['os_family'] == "Archlinux"
  - name: Show Kernel
  #ToDo 
  #figure out  OS release
  # depending  on  OS release  use  yum  apt or  pacman 
  #if  yum insall  epel  release 
  #if  pacman install  yay
  #install nano wget mc sngrep code 
  
