- name: Install Zabbix agent
  yum:
    name: "zabbix{{ ZABBIX_AGENT_VERSION }}-agent"
    state: present
    enablerepo: epel

- name: Update Zabbix server address in zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server=127.0.0.1,{{ ZABBIX_SERVER }}"
    state: present

- name: Add custom UserParameter to the end of zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    line: 'UserParameter=custom.mdstat,cat /proc/mdstat | grep -c _'
    insertafter: EOF
    state: present

- name: Enable and start Zabbix agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started

- name: Add Zabbix TCP port rule after specific line
  lineinfile:
    path: /etc/sysconfig/iptables
    line: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 10050 -j ACCEPT'
    insertafter: '^.*--dport 21064.*$'
    state: present

- name: Restart iptables to apply new rules
  systemd:
    name: iptables
    state: restarted

# If you want to use Username and Password to be authenticated by Zabbix Server
- name: Set credentials to access Zabbix Server API
  ansible.builtin.set_fact:
    ansible_user: "{{ ZABBIX_USER }}"
    ansible_httpapi_pass: "{{ ZABBIX_PASSWORD }}"

- name: Update an existing host's TLS settings
# Set current task level variables for Zabbix Server host in task
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: 80
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    #ansible_zabbix_url_path: "zabbixeu"  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
    ansible_host: "{{ ZABBIX_SERVER }}" # you can use task level ansible_host or delegate_to like in previous example
  become: false
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_default_ipv4.address }}"
    visible_name: "{{ ansible_default_ipv4.address }}"
    host_groups:
      - Hypervisors
    link_templates:
      - Template MD Soft RAID 
    force: true
    interfaces:
      - type: 1  # Agent interface (type 1 for Zabbix agent)
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"  # IP address of the host
        dns: ""
        port: "10050"  # Zabbix agent port (default 10050)


