- name: Install Zabbix agent
  yum:
    name: "zabbix{{ ZABBIX_AGENT_VERSION }}-agent"
    state: present
    enablerepo: epel

- name: Update Zabbix server address in zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server=127.0.0.1,{{ ZABBIX_SERVER }}"
    state: present

- name: Add custom UserParameter to the end of zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    line: 'UserParameter=custom.mdstat,cat /proc/mdstat | grep -c _'
    insertafter: EOF
    state: present

- name: Enable and start Zabbix agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started

- name: Add Zabbix TCP port rule after specific line
  lineinfile:
    path: /etc/sysconfig/iptables
    line: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 10050 -j ACCEPT'
    insertafter: '^.*--dport 21064.*$'
    state: present

- name: Restart iptables to apply new rules
  systemd:
    name: iptables
    state: restarted

- name: Add Zabbix host with template and group
  community.zabbix.zabbix_host:
    server_url: "http://{{ ZABBIX_SERVER }}"
    login_user: "{{ ZABBIX_API_USER }}"
    login_password: "{{ ZABBIX_API_PASSWORD }}"
    hostname: "{{ ansible_default_ipv4.address }}"
    groups:
      - "Hypervisors"
    templates:
      - "Template MD Soft RAID"
    state: present