- name: Install Zabbix agent
  yum:
    name: "zabbix{{ ZABBIX_AGENT_VERSION }}-agent"
    state: present
    enablerepo: epel

- name: Update Zabbix server address in zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    regexp: '^Server='
    line: "Server=127.0.0.1,{{ ZABBIX_SERVER }}"
    state: present

- name: Add custom UserParameter to the end of zabbix_agentd.conf
  lineinfile:
    path: /etc/zabbix_agentd.conf
    line: 'UserParameter=custom.mdstat,cat /proc/mdstat | grep -c _'
    insertafter: EOF
    state: present

- name: Enable and start Zabbix agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started

- name: Add Zabbix TCP port rule after specific line
  lineinfile:
    path: /etc/sysconfig/iptables
    line: '-A RH-Firewall-1-INPUT -p tcp -m tcp --dport 10050 -j ACCEPT'
    insertafter: '^.*--dport 21064.*$'
    state: present

- name: Restart iptables to apply new rules
  systemd:
    name: iptables
    state: restarted

- name: Authenticate with Zabbix API
  community.zabbix.zabbix_auth:
    server_url: "http://{{ ZABBIX_SERVER }}/api_jsonrpc.php"
    login_user: "{{ ZABBIX_API_USER }}"
    login_password: "{{ ZABBIX_API_PASSWORD }}"
  register: zabbix_auth  # Stores the authentication token

- name: Add Zabbix host with template and group
  community.zabbix.zabbix_host:
    host_name: "{{ ansible_default_ipv4.address }}"
    host_groups:
      - "Hypervisors"
    link_templates:
      - "Template MD Soft RAID"
    state: present
    auth_token: "{{ zabbix_auth.auth }}"