---
- name: Copy file to /usr/local/bin
  ansible.builtin.copy:
    src: "{{ file_name }}"
    dest: "/usr/local/bin/{{ file_name }}"
    mode: "0755"
    owner: root
    group: root

- name: Add cron job to run script every N days
  ansible.builtin.cron:
    name: "Sync firewall trusted list"
    job: "/usr/local/bin/{{ file_name }}"
    user: root
    minute: 0
    hour: 0
    day: "*/3" # кратно до 3
