---
- name: Install Asternic and handle MySQL prompt with verbose output
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  
  tasks:
    - name: Run make install and auto-answer MySQL prompt with empty password
      expect:
        command: make install
        responses:
          'Please enter the MySQL root password:': ''
        chdir: "/usr/src/asternic-stats-pro-2.3.14"
      register: make_output
      ignore_errors: false

    - name: Show make install output
      debug:
        var: make_output.stdout_lines
