---
- name: Clean up modules
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  strategy: free
  tasks:
    - name: Clean up modules
      shell: |
        fwconsole ma delete cxpanel
        fwconsole ma delete voipinnovations
        fwconsole ma delete xmpp
        fwconsole ma delete vega
        fwconsole ma delete sipstation

      register: count

    - debug:
        msg: "{{ count.stdout_lines | join(' ') }}"
