---
- name: Get example
  hosts: mikrotik
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Get example - ip address print
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        username: "{{ MIKROTIK_USERNAME }}"
        path: "ip address"
        port: 8728
      register: ipaddrd_printout

    - name: Dump "Get example" output
      ansible.builtin.debug:
        msg: "{{ ipaddrd_printout }}"

    - name: Add address to address list
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        username: "{{ MIKROTIK_USERNAME }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        path: "/ip/firewall/address-list"
        add: "address=1.1.1.1 list=admin_list"

    - name: Query address-list entry to remove
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        username: "{{ MIKROTIK_USERNAME }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        path: "/ip/firewall/address-list"
        query: ".id address WHERE address == 1.1.1.1"
      register: address_list_query

    - name: Dump "Remove address from address list" output
      ansible.builtin.debug:
        msg: "{{ address_list_query }}"
    - name: Remove address from address list
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        username: "{{ MIKROTIK_USERNAME }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        path: "/ip/firewall/address-list"
        remove: "{{ address_list_query.msg[0]['.id'] }}"
      when: address_list_query.msg | length > 0
