---
- name: Get example
  hosts: mikrotik
  connection: local
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Get example - ip address print
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        username: "{{ MIKROTIK_USERNAME }}"
        path: "ip address"
        port: 8728
      register: ipaddrd_printout

    - name: Dump "Get example" output
      ansible.builtin.debug:
        msg: "{{ ipaddrd_printout }}"

    - name: Add address to address list
      community.routeros.api:
        hostname: "{{ inventory_hostname }}"
        password: "{{ MIKROTIK_PASSWORD }}"
        username: "{{ MIKROTIK_USERNAME }}"
        path: "ip firewall address-list"
        add: "address-list add address=1.1.1.1 list=admin_list"
