---
- name: Add IP to Mikrotik Address List
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  strategy: free

  tasks:
    - name: Add IP to Address List
      community.routeros.routeros_command:
        commands:
          - /ip firewall address-list add list={{ address_list_name }} address={{ ip_address }} comment="Added by Ansible"
