---
- name: MikroTik API test
  hosts: all
  gather_facts: false

  tasks:
    # - name: Get IP addresses
    #   community.routeros.api:
    #     path: ip/address
    #   register: result

    # - debug:
    #     var: result
    - name: Debug ansible version

      command: ansible --version

      register: ver

    - debug:

        var: ver.stdout
