---
- name: Add IP to Mikrotik Address List
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  strategy: free

  tasks:
    - name: Add IP to Address List
      community.network.routeros_command:
        commands:
          - /ip firewall address-list add list=blocked-ips address={{ ip_address
            }} comment="Added by Ansible"
      register: result

    - debug:
        msg: "Command output: {{ result.stdout }}"
