---
# This playbook demonstrates how to run a task only on primary servers so no server2 will be pinged.
- name: Run task only on primary servers
  hosts: all
  gather_facts: false
  strategy: free
  vars:
    # Всі хости в інвентарі
    all_hosts: "{{ groups['all'] }}"

    # Вибрати лише ті, де НЕМає '2.' після префікса (тобто первинні)
    primary_names: "{{ all_hosts | reject('search', '^[^.]+2\\..+') | list }}"

  tasks:
    - name: Ping primary servers only
      ansible.builtin.ping:
      when: inventory_hostname in primary_names
    - name: Run firewall script
      ansible.builtin.script: scripts/sync-fw-trusted.sh
      when: inventory_hostname in primary_names
