---
- name: Run task only on primary servers
  hosts: all
  gather_facts: false
  strategy: free
  vars:
    # Всі хости в інвентарі
    all_hosts: "{{ groups['all'] }}"
    # Знаходимо всі backup-хости (мають '2.' після префікса)
    backup_names: "{{ all_hosts | select('search', '^[^.]+2\\..+') | list }}"
    # Витягуємо первинні імена хостів, прибравши '2' перед першою крапкою
    primary_names: "{{ backup_names | map('regex_replace', '^([^.]+)2(\\..+)', '\\1\\2') | list }}"

  tasks:
    - name: PING only primary
      ping:
      when: inventory_hostname in primary_names

    - name: Run firewall sync script
      ansible.builtin.script: scripts/sync-fw-trusted.sh
      when: inventory_hostname in primary_names
