---
- name: Secure SSH Root Login
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  strategy: free
  
  tasks:
    - name: Ensure only one PermitRootLogin line set to prohibit-password
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(\s*)PermitRootLogin\s+.*'
        line: 'PermitRootLogin prohibit-password'
        state: present
        backrefs: yes
        backup: yes
        insertafter: '^#?Authentication:'  # Insert in the correct context
        multiple: yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted