---
- name: Secure SSH Root Login
  hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  strategy: free
  
  tasks:
    - name: Uncomment and set PermitRootLogin to without-password
      replace:
        path: /etc/ssh/sshd_config
        regexp: '^#\s*PermitRootLogin\s+yes'
        replace: 'PermitRootLogin without-password'
        backup: yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted
